version: '3.9'

services:
  cassandra:
    image: cassandra:4.0.5
    container_name: cassandra
    ports:
      - 9042:9042
    volumes:
      - cassandra:/var/lib/cassandra

  redis:
    image: redis:7.0.4
    container_name: redis
    ports:
      - 6379:6379
    command: '--requirepass password'
    volumes:
      - redis:/data

  express-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-server
    ports:
      - 5000:5000
    depends_on:
      - cassandra
  
  signer:
    build:
      context: signer
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: signer
    ports:
      - 12345:12345

volumes:
  cassandra:
  redis:
