version: '3.9'

services:
  cassandra:
    image: cassandra:4.0.5
    container_name: cassandra
    ports:
      - 9042:9042
    volumes:
      - cassandra:/var/lib/cassandra
  
  express-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-server
    ports:
      - 3000:3000
    depends_on:
      - cassandra

volumes:
  cassandra:
